### ISSUE TITLE
Support serving a Site of Apps from a configuration file

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2315]
As soon as your collection of apps and scripts starts to grow, questions starts coming in

**And how do my users easily navigate the when working on the site?**
**Where do I find the code, documentation, ....?**
**Who developed or owns this particular app?**
**How can I easily manage which files to serve and where?**
**How can I customize the url of a specific app. I.e. not use `/spread_app` but `/spread-analysis` or even `/trading/spread-analysis` for my file `spread_app.py`.

In my experience a configuration file is needed. Currently no easy way to configure a site (via a configuration file) exists.

## Additional Requirements

- By default the `/` root page should show a nice Index/ Gallery page with images. Related to https://github.com/holoviz/panel/issues/2313.
- But it should also be able to serve a custom landing page at "/" and specify an alternative location like "/gallery" for the Gallery page.
- By default apps should include a nice menu to enable easy navigation across the site. Related to https://github.com/holoviz/panel/issues/2314

## Additional Context

The ability to easily serve a site from a list or glob of scripts is currently something special to Panel and should be treasured. Streamlit and Dash cannot do it. Bokeh and Voila don't have the nice gallery page that Panel now has.

- Deployments can be hard. So if you can keep to one deployment and add more apps via a configuration file it can make your time to market much faster.
- In my experience a single, micro app is not enough. Things quickly grow into multi-page apps/ larger sites.
- This can save energy resources and help make the world greener. For example deploying apps individually often means allocating a minimum of resources per app. In a Trading Environment where I am we can quickly create 10s, 100s or 1000s of apps that might not be used that often. But still needs to be available. Thus we are running a lot of resources idle.

I would like to specify something like `panel serve site.toml` and then the site is created from that with menu and nice gallery file. My current attempt to make it easy for Panel users to do this is here https://github.com/MarcSkovMadsen/awesome-analytics-apps-template

**Comment by philippjfr** [comment]
This makes a lot of sense to me. The configuration file should also support all the commandline options that you'd usually supply to `panel serve`. We should come up with a full specification of what the configuration file would look like and all the options it would support.

**Comment by jbednar** [comment]
BTW, there's a current proposal to add .ini support to Param: https://github.com/holoviz/param/issues/470 . I'm meeting with the author in a few days to plan how to incorporate those changes.

**Comment by philippjfr** [comment]
>BTW, there's a current proposal to add .ini support to Param: holoviz/param#470 . I'm meeting with the author in a few days to plan how to incorporate those changes.

Might come in useful but not that all the CLI commands are inherited from Bokeh and therefore are not param based.

**Comment by jbednar** [comment]
Sure, but isn't this newly proposed functionality?  Seems like we can accept a file and do what we want with it.

**Comment by MarcSkovMadsen** [comment]
I believe the following formats could be used for the configuration

- `.ini`
    - Pro: No need for additional dependencies as `ConfigParser` is built into python
    - Cons: Very simple format that does not support nesting.
- `.toml`:
    - Pro: Would enable Panel to store it's configuration in the `pyproject.toml` file. 
    -  I have experience storing `user` and `application` data in `.toml` files and have existing code to build on.
- `.yaml`:
    - Cons:
        - Used widely outside Python for configuration
        - Used by `conda` in the `environment.yml` and `anaconda-project.yml.` files

**Comment by MarcSkovMadsen** [comment]
And example configuration file could look like

```yaml
- environment:
    BOKEH_LOG_LEVEL: debug
- users:
    panel:
      name: HoloViz Panel
      url: https://panel.holoviz.org
      avatar: https://panel.holoviz.org/_static/logo_stacked.png
    marcskovmadsen:
      name: Marc Skov Madsen
      url: https://datamodelsanalytics.com
      email: marc.skov.madsen@gmail.com
      avatar: https://avatars.githubusercontent.com/u/42288570
      resources:
        github: https://github.com/MarcSkovMadsen
        discourse: https://discourse.holoviz.org/u/marc
    philippjfr:
      name: Philipp Rudiger
      url: https://github.com/philippjfr
      avatar: https://avatars.githubusercontent.com/u/1550771
      resources:
        github: https://github.com/philippjfr
        discourse: https://discourse.holoviz.org/u/philippjfr
- applications:
    stocks_altair:
      name: Stocks Altair
      servable: examples/gallery/apis/stocks_altair.ipynb
      url: stocks-altair
      author: philippjfr
      owner: panel
      description: An interactive stock price visualization app using Altair and YFinance
      tags:
        - Altair
        - YFinance
      resources:
        code: https://github.com/holoviz/panel/blob/master/examples/gallery/apis/stocks_altair.ipynb
    stocks_hvplot:
      name: Stocks HvPlot
      suspend: true
      servable: examples/gallery/apis/stocks_hvplot.ipynb
      url: stocks-hvplot
      author: philippjfr
      owner: panel
      description: An interactive stock price visualization app using HvPlot and YFinance
      tags:
        - HvPlot
        - YFinance
      resources:
        code: https://github.com/holoviz/panel/blob/master/examples/gallery/apis/stocks_hvplot.ipynb
```
