### ISSUE TITLE
Panel 1.0.3 interactivity not working - autompg example

### ISSUE THREAD

**Issue by matsvandecavey** [holoviz/panel#4988]
Using the new panel version, interactive plots don't update using `@pn.depends` nor `pn.bind`
(in jupyterlab, browser firefox or chrome)

**conda environment**
```yaml
name: panel_latest_jupyterlab

channels:
- pyviz
- conda-forge
- nodefaults

dependencies: 
- python>=3.7  #3.11.3
- pyviz::hvplot=*  # 0.8.3
- pyviz::datashader=*  #0.15.0
- pyviz::panel=*  #1.0.3
- jupyterlab=*  #4.0.1
```

```python
from bokeh.sampledata.autompg import autompg
columns = list(autompg.columns[:-2])

x = pn.widgets.Select(value='mpg', options=columns, name='x')
y = pn.widgets.Select(value='hp', options=columns, name='y')
color = pn.widgets.ColorPicker(name='Color', value='#AA0505')

@pn.depends(x, y, color)
def plot(xval, yval, colorval):
    return autompg.hvplot.scatter(xval, yval, c=colorval)
pn.Row(
    pn.Column('## MPG Explorer', x, y, color),
    plot

)

```
![20230531-panel-no-response](https://github.com/holoviz/panel/assets/2987662/476a3074-225b-4e25-bcfe-830155b5e932)
