### ISSUE TITLE
Vertical sliders have zero extension

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#4993]
Panel 1.0.4rc2.post1+g5ca4dcda

On 1.0.3 vertical sliders have no extension. I tried on main but the issue is still there.

```python
import panel as pn
pn.extension()

pn.Column('Panel version: ' + pn.__version__,
          pn.widgets.FloatSlider(name='Horizontal'),
          pn.widgets.FloatSlider(name='Vertical', orientation='vertical')).servable()
```

![image](https://github.com/holoviz/panel/assets/49269671/aa512a20-7f04-475c-94e5-2b0b1da16cea)

**Comment by TheoMathurin** [comment]
Ok indeed it does not work in a bokeh app either.

So maybe there was a fix in Panel somehow because it works on 0.14.4 and lower, I've used one in panel for more than a year.

**Comment by TheoMathurin** [comment]
Here is a css fix that works in Panel 1.0.4:

```css
.noUi-vertical .noUi-origin {
  top: 0%;
}
.noUi-base .noUi-connects {
  height: 200px;
}
.noUi-target.noUi-vertical {
  margin: 10px 0px 0px 25px;
}
```

The margin needs to be adapted to your layout.
