### ISSUE TITLE
Setting a sizing_mode on a Panel pane makes it jump to the end of a containing column

### ISSUE THREAD

**Issue by owenlamont** [holoviz/panel#5173]
#### ALL software version info

Browser: Vivaldi 6.1.3035.100 (Stable channel) (64-bit)
Panel 1.1.1
Pyscript 2023.05.01
Pyodide 0.23.3
Bokeh 3.1.1

#### Description of expected behavior and the observed behavior

Applying a sizing_mode to a Panel pane messes up its position in a column - I'm giving a PyScript example but tested in Jupyter and also found the formatting messed up.

#### Complete, minimal, self-contained example code that reproduces the issue

**index.html**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Panel 1.1.1 Plotly Pane Bug</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://pyscript.net/releases/2023.03.1/pyscript.css" />
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-3.1.1.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.1.1.min.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.1.1.min.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/@holoviz/panel@1.1.0/dist/panel.min.js"
    ></script>
    <script src='https://cdn.plot.ly/plotly-2.24.1.min.js'></script>
    <link rel="stylesheet" href="https://pyscript.net/releases/2023.05.1/pyscript.css"/>
    <script defer src="https://pyscript.net/releases/2023.05.1/pyscript.js"></script>
</head>
<body>
    <py-config src="./pyscript.toml"></py-config>
    <py-script src="./main.py"></py-script>
    <div id="plot"></div>
</body>
</html>
```

**main.py**
```python
import panel as pn

pn.Column(
    pn.pane.Plotly(sizing_mode="scale_both"),
    pn.pane.Alert("Why am I at the top?", sizing_mode="stretch_width")
).servable(target='plot')
```

**pyscript.toml**
```toml
packages = [
    "https://cdn.holoviz.org/panel/1.1.0/dist/wheels/bokeh-3.1.1-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/1.1.0/dist/wheels/panel-1.1.0-py3-none-any.whl", 
    "plotly==5.15.0",
]
name = "Panel 1.1.1 Plotly Pane Bug"
[[interpreters]]
src = "https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.js"
name = "pyodide-0.23.3"
lang = "python"
```

#### Screenshots or screencasts of the bug in action
**pyscript**
![image](https://github.com/holoviz/panel/assets/12672027/9c794e2f-7531-436f-815e-53059b81c730)

**jupyter**
![image](https://github.com/holoviz/panel/assets/12672027/13ed0614-d68b-430c-86ec-fa6d37e99cb7)
