### ISSUE TITLE
Matplotlib Pane not respecting dpi of target Matplotlib Figure

### ISSUE THREAD

**Issue by owenlamont** [holoviz/panel#5174]
#### ALL software version info
Browser: Vivaldi 6.1.3035.100 (Stable channel) (64-bit)
Bokeh 3.1.1
Matplotlib 3.5.2
Panel 1.1.1
Pyscript 2023.05.01
Pyodide 0.23.3

#### Description of expected behavior and the observed behavior
I expected Matplotlib pane rasters to scale according to the specified dpi of their Matplotlib figures, but when created multiple Matplotlib panes and figures where the figures had different DPIs set it looks like my specified DPI was always overwritten to be 144 DPI regardless of what I set the Matplotlib figure to have (I checked and the Matplotlib figures do have the correct dpis set internally still, something must be overriding it later in the render pipeline).

Example is PyScript but I got the same behaviour when testing Panel 1.1.1 in Jupyter with a local environment

#### Complete, minimal, self-contained example code that reproduces the issue

**index.html**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Panel 1.1.1 Matplotlib Pane Resolution</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://pyscript.net/releases/2023.05.1/pyscript.css" />
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-3.1.1.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.1.1.min.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.1.1.min.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/@holoviz/panel@1.1.1/dist/panel.min.js"
    ></script>
    <link rel="stylesheet" href="https://pyscript.net/releases/2023.05.1/pyscript.css"/>
    <script defer src="https://pyscript.net/releases/2023.05.1/pyscript.js"></script>
</head>
<body>
    <py-config src="./pyscript.toml"></py-config>
    <py-script src="./main.py"></py-script>
    <div id="plot"></div>
</body>
</html>
```

**main.py**
```python
import panel as pn
import matplotlib.pyplot as plt

fig_100x100, _ = plt.subplots(figsize=(1, 1), dpi=100)
fig_200x200, _ = plt.subplots(figsize=(1, 1), dpi=200)

pn.Column(
    pn.pane.Markdown("# This plot should be 100px by 100px"),
    pn.pane.Matplotlib(object=fig_100x100).servable(target='plot'),
    pn.pane.Markdown("# This plot should be 200px by 200px"),
    pn.pane.Matplotlib(object=fig_200x200).servable(target='plot'),
    pn.pane.Markdown("# Actually these both came out as 144px by 144px")
)
```

**pyscript.toml**
```toml
packages = [
    "https://cdn.holoviz.org/panel/1.1.1/dist/wheels/bokeh-3.1.1-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/1.1.1/dist/wheels/panel-1.1.1-py3-none-any.whl",
    "matplotlib"
]
name = "Panel 1_1_1 Matplotlib Pane Resolution"
[[interpreters]]
src = "https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.js"
name = "pyodide-0.23.3"
lang = "python"
```

#### Screenshots or screencasts of the bug in action

**PyScript**
![image](https://github.com/holoviz/panel/assets/12672027/ed6d7d74-287d-45e0-8fb7-569cd1e33a7c)

**Jupyter**
![image](https://github.com/holoviz/panel/assets/12672027/695f7cf8-f31f-4721-a835-a54008d1788b)
