### ISSUE TITLE
FloatInput widget shows a NaN value when its input is cleared in PyScript

### ISSUE THREAD

**Issue by owenlamont** [holoviz/panel#5205]
#### ALL software version info

**PyScript**
Browser: Vivaldi 6.1.3035.111 (Stable channel) (64-bit) 
Panel 1.1.1
Pyscript 2023.05.01
Pyodide 0.23.3
Bokeh 3.1.1

#### Description of expected behavior and the observed behavior

Create a FloatInput widget then clear/delete its value. In PyScript it will now show the value NaN but when its value is queried it returns None - not NaN. In a regular Python environment its displayed value just remains clear rather than showing NaN (which I assume is the correct behavior).

#### Complete, minimal, self-contained example code that reproduces the issue

**index.thml**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Panel FloatInput</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-3.1.1.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.1.1.min.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.1.1.min.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/@holoviz/panel@1.1.1/dist/panel.min.js"
    ></script>
    <link rel="stylesheet" href="https://pyscript.net/releases/2023.05.1/pyscript.css"/>
    <script defer src="https://pyscript.net/releases/2023.05.1/pyscript.js"></script>
</head>
<body>
    <py-config src="./pyscript.toml"></py-config>
    <py-script src="./main.py"></py-script>
    <div id="plot"></div>
</body>
</html>
```

**main.py**
```python
import panel as pn
import math

float_input = pn.widgets.FloatInput()

float_input.servable(target="plot")

def float_input_callback(event):
    print(event.new)
    print(event.new is None)

float_input_watcher = float_input.param.watch(
    float_input_callback, "value"
)
```

**pyscript.toml**
```toml
packages = [
    "https://cdn.holoviz.org/panel/1.1.1/dist/wheels/bokeh-3.1.1-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/1.1.1/dist/wheels/panel-1.1.1-py3-none-any.whl", 
]
name = "Panel Plotly Float Input"
[[interpreters]]
src = "https://cdn.jsdelivr.net/pyodide/v0.23.3/full/pyodide.js"
name = "pyodide-0.23.3"
lang = "python"
```

#### Screenshots or screencasts of the bug in action

![image](https://github.com/holoviz/panel/assets/12672027/13dc9bc7-6cd1-44a3-9559-63cf20ba82e8)

![image](https://github.com/holoviz/panel/assets/12672027/b706f3e9-97d3-4208-9af0-586f49d0eec2)
