### ISSUE TITLE
Cannot read links in Tabulator table when using Fast Template

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6145]
Panel==1.3.6

```python
import panel as pn
import pandas as pd

pn.extension("tabulator", template="fast")

link = "https://panel.holoviz.org"

data = pd.DataFrame({
    "x": [1,2],
    "Source": [link, link]
})

tabulator_formatters = {
    "Source": {"type": "link", "target": "_blank", "label": "link"},
}
pn.widgets.Tabulator(data, formatters=tabulator_formatters, sizing_mode="stretch_width").servable()
```

![image](https://github.com/holoviz/panel/assets/42288570/2fc73461-cc46-4822-883f-404ff4a8e387)

There is a similar issue when hovering over a row.

## Workaround
Use `raw_css`

```css
.tabulator-row.tabulator-selected a {color: var(--foreground-on-accent-rest);}
.tabulator-row.tabulator-selectable:hover a {color: var(--foreground-on-accent-rest);}
```
