### ISSUE TITLE
tabulator default font size is too large

### ISSUE THREAD

**Issue by samimia-swks** [holoviz/panel#7100]
Using panel 1.4.4 with bootstrap template, I have noticed that normal text (e.g. markdown panel) renders in 12px size but the tabulator widget uses 16px, which looks pretty odd: 

![image](https://github.com/user-attachments/assets/7ebf310d-de01-45c6-8f33-a6d92d58417c)

There is no option I can see to adjust the font size of the tabulator widget. I feel like either the default should be adjusted or a mechanism to easily change font should be provided. 

As a workaround, I am using this custom css stylesheet: 
``` css
tabulator_css = ".tabulator-cell {font-size: 12px;} .tabulator-col-title {font-size: 12px;}"
```
