### ISSUE TITLE
Token issue when using oauth encryption key

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#7909]
# WebSocket connection failures with Azure OAuth due to large token size

## Issue Description

When using Panel with Azure OAuth authentication on a Kubernetes deployment behind an ingress controller, WebSocket connections fail due to excessively large authentication tokens (10,183 bytes), causing the application to be unusable. The issue only occurs when using the `--oauth-encryption-key` parameter, which significantly increases token size (from 7,530 to 10,183 bytes).

## Environment

- Panel version: Current development version
- Deployment: Kubernetes with NGINX ingress controller
- Authentication: Azure OAuth
- Browser: Chrome/Edge (latest)

## Steps to Reproduce

1. Deploy a simple Panel application in Kubernetes with Azure OAuth authentication
2. Configure the application with `--oauth-encryption-key` parameter
3. Access the application through an ingress controller
4. Attempt to log in

## Expected Behavior

The application should successfully establish a WebSocket connection after authentication and work as expected.

## Actual Behavior

After authentication, the WebSocket connection fails with errors in the browser console:
<details>
<summary>Console Error Details</summary>

```
[bokeh 3.7.2] setting log level to: 'trace'
WebSocket connection to 'wss://example.org/apps/panel-oauth-app/script/ws' failed
[bokeh 3.7.2] Failed to connect to Bokeh server: Could not open websocket
[bokeh 3.7.2] Failed to load Bokeh session XXXXXXXXXXXXXXXXXXXXXXXXXXXX: Error: Could not open websocket
Error rendering Bokeh items: Error: Could not open websocket
[bokeh 3.7.2] Lost websocket 0 connection, 1006 ()
[bokeh 3.7.2] Websocket connection 0 disconnected, will not attempt to reconnect
```

The issue appears to be in the JavaScript code where it attempts to create a WebSocket connection:
```javascript
new WebSocket(e,["bokeh", this.token])
```
where `this.token` is 10,183 bytes when using `--oauth-encryption-key`.
</details>

## Analysis

I've confirmed that the large token size is causing the issue by testing with and without the `--oauth-encryption-key` parameter:

1. **With encryption key** (fails):
   - Token size: 10,183 bytes
   - Command:
<details>
<summary>Panel command with encryption key</summary>

```bash
panel serve script.py --oauth-provider=azure \
  --oauth-key='CLIENT_ID' \
  --oauth-secret='CLIENT_SECRET' \
  --cookie-secret='COOKIE_SECRET' \
  --oauth-encryption-key='ENCRYPTION_KEY' \
  --oauth-extra-params "{'tenant': 'TENANT_ID'}" \
  --oauth-redirect-uri=https://example.org/apps/panel-oauth-app/ \
  --address 0.0.0.0 --port 5006 --num-threads=0 --num-procs=1 \
  --allow-websocket-origin=example.org \
  --prefix=apps/panel-oauth-app
```
</details>

2. **Without encryption key** (works):
   - Token size: 7,530 bytes
   - Command:
<details>
<summary>Panel command without encryption key</summary>

```bash
panel serve script.py --oauth-provider=azure \
  --oauth-key='CLIENT_ID' \
  --oauth-secret='CLIENT_SECRET' \
  --cookie-secret='COOKIE_SECRET' \
  --oauth-extra-params "{'tenant': 'TENANT_ID'}" \
  --oauth-redirect-uri=https://example.org/apps/panel-oauth-app/ \
  --address 0.0.0.0 --port 5006 --num-threads=0 --num-procs=1 \
  --allow-websocket-origin=example.org \
  --prefix=apps/panel-oauth-app
```
</details>

## Attempted Solutions

1. **Increased buffer sizes in Ingress configuration**:
<details>
<summary>Ingress Configuration</summary>

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: panel-oauth-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "150m"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "512k"
    nginx.ingress.kubernetes.io/client-header-buffer-size: "512k"
    nginx.ingress.kubernetes.io/http2-max-header-size: "512k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "8 512k"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "512k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/websocket-services: "panel-oauth-app"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
```
</details>

This approach didn't solve the issue. I attempted to add additional `server-snippet` configurations, but these are blocked by the cluster administrator:

```
error when patching: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: 
nginx.ingress.kubernetes.io/server-snippet annotation cannot be used. 
Snippet directives are disabled by the Ingress administrator
```

2. **Direct access without Ingress**: Accessing the application directly via port forwarding works fine, confirming that the issue is related to the ingress/proxy configuration.

## Feature Request/Enhancement

Panel should implement one of these solutions to handle large authentication tokens:

1. **Cookie compression**: Add a way to compress the authentication token before sending it in WebSocket headers to reduce its size.

2. **Token size reduction**: Make the encrypted token format more compact or allow customizing which fields are included in the token.

3. **Alternative authentication method for WebSockets**: Implement a more efficient authentication mechanism for WebSocket connections that doesn't require passing the entire token.

4. **Documentation**: Add documentation specifically addressing the WebSocket connection issues with large tokens and how to configure proxies/ingress controllers appropriately.

## Additional Context

The application is deployed as a JupyterHub sidecar container in Kubernetes with the following service configuration:

<details>
<summary>Service Configuration</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: panel-oauth-app
  namespace: jupyter
  labels:
    project: panel
    app: jupyter
spec:
  ports:
  - port: 80
    targetPort: 5006
    protocol: TCP
  selector:
    app.kubernetes.io/component: singleuser-server
    hub.jupyter.org/username: user
```
</details>

## Workaround

Currently, the only working workaround is to run without the `--oauth-encryption-key` parameter, which may have security implications depending on the use case according to CoPilot.
