### ISSUE TITLE
support Authorization Code Flow with Proof Key for Code Exchange (PKCE)

### ISSUE THREAD

**Issue by sean-landry** [holoviz/panel#7979]
#### ALL software version info

<details>
    <summary>Software Version Info</summary>

```plaintext
OS :  Fedora Linux 42

Python 3.11.12

pip list

Package            Version
------------------ -----------
bleach             6.2.0
bokeh              3.7.3
certifi            2025.4.26
cffi               1.17.1
charset-normalizer 3.4.2
contourpy          1.3.2
cryptography       45.0.4
idna               3.10
Jinja2             3.1.6
linkify-it-py      2.0.3
Markdown           3.8
markdown-it-py     3.0.0
MarkupSafe         3.0.2
mdit-py-plugins    0.4.2
mdurl              0.1.2
narwhals           1.42.0
numpy              2.3.0
packaging          25.0
pandas             2.3.0
panel              1.7.1
param              2.2.1
pillow             11.2.1
pip                24.3.1
pycparser          2.22
python-dateutil    2.9.0.post0
pytz               2025.2
pyviz_comms        3.0.4
PyYAML             6.0.2
requests           2.32.4
setuptools         74.1.3
six                1.17.0
tornado            6.5.1
tqdm               4.67.1
typing_extensions  4.14.0
tzdata             2025.2
uc-micro-py        1.0.3
urllib3            2.4.0
webencodings       0.5.1
xyzservices        2025.4.0

```
</details>

#### Description of expected behavior and the observed behavior

*Expected behavior*

I expect the authentication flow to be successful when using the panel `auth_code`  oauth_provider configuration with the [Dex OpenId Connect Provider](https://dexidp.io/).

*Observed behavior*

The authentication flow fails because the client_secret and code_verifier parameters are not included in the query parameters when fetching the access token from Dex, which uses the Authorization Code Flow with Proof Key for Code Exchange (PKCE).

#### Complete, minimal, self-contained example code that reproduces the issue

Create a minimal configuration file for Dex:

```yaml
# dex-config.yaml
frontend:
  issuer: localhost
issuer: http://localhost:5556/oidc
enablePasswordDB: true
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
web:
  http: localhost:5556
oauth2:
  skipApprovalScreen: true
staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
staticClients:
  - id: panel
    name: 'panel'
    secret: panel
    redirectURIs:
      - 'http://localhost:5006/login'
```

Use this docker-compose.yaml file to start Dex:

```yaml
# docker-compose.yaml
services:
  dex:
    image: ghcr.io/dexidp/dex:v2.31.1
    ports:
      - "5556:5556"
    volumes:
      - ./dex-config.yaml:/etc/dex/cfg/config.yaml:z
    command: ["dex", "serve", "/etc/dex/cfg/config.yaml"]
    network_mode: host
```

Start Dex:

```bash
docker compose up
```

Serve the troubleshooting script found in the [documentation](https://panel.holoviz.org/how_to/authentication/trouble_shooting.html#debugging) with panel.

```bash
BOKEH_LOG_LEVEL=trace \
BOKEH_PY_LOG_LEVEL=debug \
PANEL_LOG_LEVEL=debug \
panel serve script.py \
--oauth-provider='auth_code' \
--oauth-key='panel' \
--oauth-secret='panel' \
--oauth-extra-params='{"AUTHORIZE_URL": "http://localhost:5556/oidc/auth", "TOKEN_URL": "http://localhost:5556/oidc/token", "USER_URL": "http://localhost:5556/oidc/userinfo"}' \
--cookie-secret='fdb0Yy-wHDyoCUeRyvPnl07zjIOINImqY5aaGDDJbqM=' \
--oauth-encryption-key='1txhYRzdbCpBRKKcvyChR0qH9QSm60BU4UJq0NqZz2I=' \
--port='5006' \
--allow-websocket-origin='localhost:5006' \
--oauth-redirect-uri='http://localhost:5006/login'
```

Open http://localhost:5006/script in the web browser and complete the Dex login form.

username: admin@example.com
password: password

![Image](https://github.com/user-attachments/assets/194f8f9c-2873-4567-8475-d2136bb98bbf)

Click login and the "Invalid client credentials" error is displayed in the panel UI.

![Image](https://github.com/user-attachments/assets/85335bf6-6a74-4f84-8dd5-1691c2fd98c3)

#### Stack traceback and/or browser JavaScript console output

The panel logs display:

```
2025-06-11 16:05:07,695 DEBUG: panel.auth - CodeChallengeLoginHandler making access token request.
2025-06-11 16:05:07,699 DEBUG: panel.auth - CodeChallengeLoginHandler access token request failed.
2025-06-11 16:05:07,699 ERROR: panel.auth - CodeChallenge OAuth provider returned a HTTP 401: Unauthorized error. The full response was: {'error': 'invalid_client', 'error_description': 'Invalid client credentials.'}
2025-06-11 16:05:07,699 401 GET /login?code=w2tm3ieclmt6danp66ebvwpss&state=eyJzdGF0ZV9pZCI6ICI1MmIyNjNlNzNiYWY0ZGM1YTY3MDY3OTgzNzFiODAwOSIsICJuZXh0X3VybCI6ICIvc2NyaXB0In0%3D (127.0.0.1): Invalid client credentials.
```

The Dex logs display:

```
dex-1  | time="2025-06-11T19:32:42Z" level=info msg="login successful: connector \"local\", username=\"admin\", preferred_username=\"\", email=\"admin@example.com\", groups=[]"
dex-1  | time="2025-06-11T19:32:42Z" level=info msg="missing client_secret on token request for client: panel"
```

#### Screenshots or screencasts of the bug in action

- [x] I may be interested in making a pull request to address this

After exploring the code base I found that if I make the following changes everything works as expected:

1.  add the "client_secret" as a kwarg to this function call of the `CodeChallengeLoginHandler` class :

https://github.com/holoviz/panel/blob/a22c3b82cf654a5ac3fa1e5e072f384301d61b17/panel/auth.py#L576

my changes:

```diff
- user = await self.get_authenticated_user(redirect_uri, config.oauth_key, url_state, code=code)
+ user = await self.get_authenticated_user(redirect_uri, config.oauth_key, url_state, client_secret = config.oauth_secret, code=code)
```

2.   modify the `async def _fetch_access_token` function of the `OAuthLoginHandler` to include the "code_verifier" parameter

https://github.com/holoviz/panel/blob/a22c3b82cf654a5ac3fa1e5e072f384301d61b17/panel/auth.py#L207-L220

my changes:

```diff
        if code:
            params['code'] = code
+            params['code_verifier'] = self.get_code_cookie()
        if refresh_token:
            refreshing = True
            params['refresh_token'] = refresh_token
            params['grant_type'] = 'refresh_token'
        else:
            refreshing = False
        if client_secret:
            params['client_secret'] = client_secret
        elif username:
            params.update(username=username, password=password)
        else:
            params['code_verifier'] = self.get_code_cookie()
```

After making those changes the Authorization Code Flow with Proof Key for Code Exchange (PKCE) works as expected and I am redirected back to the panel app

![Image](https://github.com/user-attachments/assets/78132b71-86e2-4749-8b57-b4ff6d05ef58)

it is unclear to me if this is a bug report or a request to support the Authorization Code Flow with Proof Key for Code Exchange (PKCE)
